// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6IJqcf0SMfZQSfCdvacJrFE8PIDNFok',
    appId: '1:6798105449:web:d6c49786d6258e88ddfbf8',
    messagingSenderId: '6798105449',
    projectId: 'payperview-bc36c',
    authDomain: 'payperview-bc36c.firebaseapp.com',
    storageBucket: 'payperview-bc36c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTj7-FAJfPOmjavUxHM-X0hqpLnM-_5QM',
    appId: '1:6798105449:android:365b0d2ec16d583cddfbf8',
    messagingSenderId: '6798105449',
    projectId: 'payperview-bc36c',
    storageBucket: 'payperview-bc36c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5XKYEGrc5uA10wOrxbwjzauXtKAJZtG0',
    appId: '1:6798105449:ios:6bf995f726dbbc0eddfbf8',
    messagingSenderId: '6798105449',
    projectId: 'payperview-bc36c',
    storageBucket: 'payperview-bc36c.appspot.com',
    iosBundleId: 'com.example.payPerView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5XKYEGrc5uA10wOrxbwjzauXtKAJZtG0',
    appId: '1:6798105449:ios:d200b0282cd3e5d4ddfbf8',
    messagingSenderId: '6798105449',
    projectId: 'payperview-bc36c',
    storageBucket: 'payperview-bc36c.appspot.com',
    iosBundleId: 'com.example.payPerView.RunnerTests',
  );
}
